# Generated by Django 5.2.11 on 2026-02-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_cardio_user_alter_supplement_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardio',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='supplement',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-date', '-name']},
        ),
        migrations.CreateModel(
            name='StepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
