# Generated by Django 5.2.11 on 2026-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_nutrition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrition',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='nutrition',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
    ]
