# Generated by Django 5.2.11 on 2026-03-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_nutrition_options_nutrition_ai_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(default='Fitness Tips', max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
