FROM python:3.9.15

WORKDIR /app

RUN python -m venv /app/venv

ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY server/ /app/server/

WORKDIR /app/server

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
